[package]
name = "epoch_markers"
description = "CBOR-focused encoders/decoders for Epoch Marker structures"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/carl-wallace/cbor-formats/tree/main/epoch_markers"
categories = ["cryptography", "data-structures", "encoding", "no-std", "parser-implementations"]
keywords = ["cbor", "json", "epoch-markers", "rats", "attestation"]
readme = "README.md"
version = "0.1.1"
edition = "2024"
rust-version = "1.88.0"

[dependencies]
cbor_derive = { version = "0.1.1", path = "../cbor_derive" }
common = { version = "0.1.1", path = "../common" }
etime = { version = "0.1.1", path = "../etime" }
ciborium = "0.2.2"
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_bytes = "0.11"

[dev-dependencies]
hex-literal = "1.1.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
