# Trigger a full workspace run
[workspace]
resolver = "2"
members = [
    "ar4si",
    "cbor_derive",
    "cfcli",
    "cmw",
    "common",
    "coserv",
    "corim",
    "cose",
    "cose_crypto",
    "coswid",
    "cots",
    "ear",
    "eat",
    "epoch_markers",
    "etime",
    "jose",
    "webauthn_asf"
]

[profile.dev]
opt-level = 2