//! Array-based structs from the Concise Reference Integrity Manifest (CoRIM) spec
//! ([draft-ietf-rats-corim-10]).
//!
//! This module implements the following CDDL productions:
//!
//! | CDDL | Rust |
//! |------|------|
//! | `reference-triple-record` | [`ReferenceTripleRecord`] / [`ReferenceTripleRecordCbor`] |
//! | `endorsed-triple-record` | [`EndorsedTripleRecord`] / [`EndorsedTripleRecordCbor`] |
//! | `identity-triple-record` | [`IdentityTripleRecord`] / [`IdentityTripleRecordCbor`] |
//! | `attest-key-triple-record` | [`AttestKeyTripleRecord`] / [`AttestKeyTripleRecordCbor`] |
//! | `coswid-triple-record` | [`CoswidTripleRecord`] / [`CoswidTripleRecordCbor`] |
//! | `domain-dependency-triple-record` | [`DomainDependencyTripleRecord`] / [`DomainDependencyTripleRecordCbor`] |
//! | `domain-membership-triple-record` | [`DomainMembershipTripleRecord`] / [`DomainMembershipTripleRecordCbor`] |
//! | `conditional-endorsement-triple-record` | [`ConditionalEndorsementTripleRecord`] / [`ConditionalEndorsementTripleRecordCbor`] |
//! | `stateful-environment-record` | [`StatefulEnvironmentRecord`] / [`StatefulEnvironmentRecordCbor`] |
//! | `conditional-series-record` | [`ConditionalSeriesRecord`] / [`ConditionalSeriesRecordCbor`] |
//! | `conditional-endorsement-series-triple-record` | [`ConditionalEndorsementSeriesTripleRecord`] / [`ConditionalEndorsementSeriesTripleRecordCbor`] |
//! | `conditional-endorsement-series-condition` | [`ConditionalEndorsementSeriesCondition`] / [`ConditionalEndorsementSeriesConditionCbor`] |
//!
//! Each struct has a companion `*Cbor` type generated by the
//! [`StructToArray`] macro for direct CBOR array serialization.
//!
//! [draft-ietf-rats-corim-10]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10

use ciborium::{cbor, value::Value};
use core::{fmt, marker::PhantomData};
use serde::ser::Error as OtherError;
use serde::{Deserialize, Serialize};
use serde::{de::Error, de::Visitor};

use alloc::{vec, vec::Vec};

use crate::choices::*;
use crate::maps::*;
use alloc::format;
use alloc::string::String;
use cbor_derive::StructToArray;

/// The `attest-key-triple-record` type is defined in [CoRIM Section 5.1.10].
///
/// ```text
/// attest-key-triple-record = [
///   environment: environment-map
///   key-list: [ + $crypto-key-type-choice ]
///   ? conditions: non-empty<{
///     ? &(mkey: 0) => $measured-element-type-choice,
///     ? &(authorized-by: 1) => [ + $crypto-key-type-choice ]
///   }>
/// ]
/// ```
///
/// [CoRIM Section 5.1.10]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.10
#[derive(Clone, Debug, PartialEq, StructToArray, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct AttestKeyTripleRecord {
    #[cbor(value = "Map", cbor = "true")]
    pub environment: EnvironmentMap,
    #[cbor(value = "Array")]
    pub key_list: Vec<CryptoKeyTypeChoice>,
    #[cbor(value = "Map", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conditions: Option<AttestKeyConditionsMap>,
}

/// The `coswid-triple-record` type is defined in [CoRIM Section 5.1.12].
///
/// ```text
/// coswid-triple-record = [
///   environment-map
///   [ + concise-swid-tag-id ]
/// ]
/// ```
///
/// [CoRIM Section 5.1.12]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.12
#[derive(Clone, Debug, PartialEq, StructToArray, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct CoswidTripleRecord {
    #[cbor(value = "Map", cbor = "true")]
    pub environment_map: EnvironmentMap,
    #[cbor(value = "Array", cbor = "true")]
    pub tag_ids: Vec<TagIdTypeChoice>,
}

/// The `domain-dependency-triple-record` type is defined in [CoRIM Section 5.1.11.2].
///
/// ```text
/// domain-dependency-triple-record = [
///   domain-id: domain-type
///   trustees: [ + domain-type ]
/// ]
/// ```
///
/// [CoRIM Section 5.1.11.2]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.11.2
#[derive(Clone, Debug, PartialEq, StructToArray, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct DomainDependencyTripleRecord {
    pub domain_id: DomainTypeChoice,
    #[cbor(value = "Array")]
    pub trustees: Vec<DomainTypeChoice>,
}

/// The `domain-membership-triple-record` type is defined in [CoRIM Section 5.1.11.1].
///
/// ```text
/// domain-membership-triple-record = [
///   domain-id: domain-type
///   members: [ + domain-type ]
/// ]
/// ```
///
/// [CoRIM Section 5.1.11.1]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.11.1
#[derive(Clone, Debug, PartialEq, StructToArray, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct DomainMembershipTripleRecord {
    pub domain_id: DomainTypeChoice,
    #[cbor(value = "Array")]
    pub members: Vec<DomainTypeChoice>,
}

/// The `endorsed-triple-record` type is defined in [CoRIM Section 5.1.6].
///
/// ```text
/// endorsed-triple-record = [
///   environment-map
///   [ + measurement-map ]
/// ]
/// ```
///
/// [CoRIM Section 5.1.6]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.6
#[derive(Clone, Debug, PartialEq, StructToArray, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct EndorsedTripleRecord {
    #[cbor(value = "Map", cbor = "true")]
    pub environment_map: EnvironmentMap,
    #[cbor(value = "Array", cbor = "true")]
    pub measurement_map: Vec<MeasurementMap>,
}

/// The `identity-triple-record` type is defined in [CoRIM Section 5.1.9].
///
/// ```text
/// identity-triple-record = [
///   environment: environment-map
///   key-list: [ + $crypto-key-type-choice ]
///   ? conditions: non-empty<{
///     ? &(mkey: 0) => $measured-element-type-choice,
///     ? &(authorized-by: 1) => [ + $crypto-key-type-choice ]
///   }>
/// ]
/// ```
///
/// [CoRIM Section 5.1.9]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.9
#[derive(Clone, Debug, PartialEq, StructToArray, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct IdentityTripleRecord {
    #[cbor(value = "Map", cbor = "true")]
    pub environment: EnvironmentMap,
    #[cbor(value = "Array")]
    pub key_list: Vec<CryptoKeyTypeChoice>,
    #[cbor(value = "Map", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conditions: Option<AttestKeyConditionsMap>,
}

/// The `reference-triple-record` type is defined in [CoRIM Section 5.1.5].
///
/// ```text
/// reference-triple-record = [
///   environment-map
///   [ + measurement-map ]
/// ]
/// ```
///
/// [CoRIM Section 5.1.5]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.5
#[derive(Clone, Debug, PartialEq, StructToArray, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct ReferenceTripleRecord {
    #[cbor(value = "Map", cbor = "true")]
    #[serde(rename = "environment")]
    pub environment_map: EnvironmentMap,
    #[cbor(value = "Array", cbor = "true")]
    #[serde(rename = "measurements")]
    pub measurement_map: Vec<MeasurementMap>,
}

/// The `conditional-endorsement-triple-record` type is defined in [CoRIM Section 5.1.7].
///
/// ```text
/// conditional-endorsement-triple-record = [
///   conditions: [ + stateful-environment-record ]
///   endorsements: [ + endorsed-triple-record ]
/// ]
/// ```
///
/// [CoRIM Section 5.1.7]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.7
#[derive(Clone, Debug, PartialEq, StructToArray, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct ConditionalEndorsementTripleRecord {
    #[cbor(value = "Array", cbor = "true")]
    pub conditions: Vec<StatefulEnvironmentRecord>,
    #[cbor(value = "Array", cbor = "true")]
    pub endorsements: Vec<EndorsedTripleRecord>,
}

/// The `stateful-environment-record` type is defined in [CoRIM Section 5.1.7].
///
/// ```text
/// stateful-environment-record = [
///   environment: environment-map,
///   claims-list: [ + measurement-map ]
/// ]
/// ```
///
/// [CoRIM Section 5.1.7]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.7
#[derive(Clone, Debug, PartialEq, StructToArray, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct StatefulEnvironmentRecord {
    #[cbor(value = "Map", cbor = "true")]
    pub environment: EnvironmentMap,
    #[cbor(value = "Array", cbor = "true")]
    pub claims_list: Vec<MeasurementMap>,
}

/// The `conditional-series-record` type is defined in [CoRIM Section 5.1.8].
///
/// ```text
/// conditional-series-record = [
///   selection: [ + measurement-map ]
///   addition: [ + measurement-map ]
/// ]
/// ```
///
/// [CoRIM Section 5.1.8]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.8
#[derive(Clone, Debug, PartialEq, StructToArray, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct ConditionalSeriesRecord {
    #[cbor(value = "Array", cbor = "true")]
    pub selection: Vec<MeasurementMap>,
    #[cbor(value = "Array", cbor = "true")]
    pub addition: Vec<MeasurementMap>,
}

/// The condition in a `conditional-endorsement-series-triple-record`, defined in
/// [CoRIM Section 5.1.8].
///
/// ```text
/// condition = [
///   environment: environment-map,
///   claims-list: [ * measurement-map ],
///   ? authorized-by: [ + $crypto-key-type-choice ]
/// ]
/// ```
///
/// [CoRIM Section 5.1.8]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.8
#[derive(Clone, Debug, PartialEq, StructToArray, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct ConditionalEndorsementSeriesCondition {
    #[cbor(value = "Map", cbor = "true")]
    pub environment: EnvironmentMap,
    #[cbor(value = "Array", cbor = "true")]
    pub claims_list: Vec<MeasurementMap>,
    #[cbor(value = "Array")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub authorized_by: Option<Vec<CryptoKeyTypeChoice>>,
}

/// The `conditional-endorsement-series-triple-record` type is defined in [CoRIM Section 5.1.8].
///
/// ```text
/// conditional-endorsement-series-triple-record = [
///   condition: [
///     environment: environment-map,
///     claims-list: [ * measurement-map ],
///     ? authorized-by: [ + $crypto-key-type-choice ]
///   ]
///   series: [ + conditional-series-record ]
/// ]
/// ```
///
/// [CoRIM Section 5.1.8]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.8
#[derive(Clone, Debug, PartialEq, StructToArray, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct ConditionalEndorsementSeriesTripleRecord {
    #[cbor(cbor = "true")]
    pub condition: ConditionalEndorsementSeriesCondition,
    #[cbor(value = "Array", cbor = "true")]
    pub series: Vec<ConditionalSeriesRecord>,
}
