//! Map-based structs from the Concise Reference Integrity Manifest (CoRIM) spec
//! ([draft-ietf-rats-corim-10]).
//!
//! This module implements the following CDDL productions:
//!
//! | CDDL | Rust |
//! |------|------|
//! | `unsigned-corim-map` | [`CorimMap`] / [`CorimMapCbor`] |
//! | `corim-meta-map` | [`CorimMetaMap`] / [`CorimMetaMapCbor`] |
//! | `corim-signer-map` | [`CorimSignerMap`] / [`CorimSignerMapCbor`] |
//! | `corim-locator-map` | [`CorimLocatorMap`] / [`CorimLocatorMapCbor`] |
//! | `concise-mid-tag` | [`ConciseMidTag`] / [`ConciseMidTagCbor`] |
//! | `class-map` | [`ClassMap`] / [`ClassMapCbor`] |
//! | `environment-map` | [`EnvironmentMap`] / [`EnvironmentMapCbor`] |
//! | `measurement-map` | [`MeasurementMap`] / [`MeasurementMapCbor`] |
//! | `measurement-values-map` | [`MeasurementValuesMap`] / [`MeasurementValuesMapCbor`] |
//! | `flags-map` | [`FlagsMap`] / [`FlagsMapCbor`] |
//! | `entity-map` | [`EntityMap`] / [`EntityMapCbor`] |
//! | `tag-identity-map` | [`TagIdentityMap`] / [`TagIdentityMapCbor`] |
//! | `linked-tag-map` | [`LinkedTagMap`] / [`LinkedTagMapCbor`] |
//! | `triples-map` | [`TriplesMap`] / [`TriplesMapCbor`] |
//! | `validity-map` | [`ValidityMap`] / [`ValidityMapCbor`] |
//! | `version-map` | [`VersionMap`] / [`VersionMapCbor`] |
//! | `protected-corim-header-map` | [`ProtectedCorimHeaderMap`] / [`ProtectedCorimHeaderMapCbor`] |
//! | `attest-key-conditions-map` | [`AttestKeyConditionsMap`] / [`AttestKeyConditionsMapCbor`] |
//! | `concise-tl-tag` | [`ConciseTlTag`] / [`ConciseTlTagCbor`] |
//!
//! Each struct has a companion `*Cbor` type generated by the
//! [`StructToMap`] macro for direct CBOR map serialization.
//!
//! [draft-ietf-rats-corim-10]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10

use alloc::collections::BTreeMap;
use alloc::format;
use alloc::string::{String, ToString};
use alloc::{vec, vec::Vec};
use ciborium::{cbor, value::Value};
use core::{fmt, marker::PhantomData};
use serde::de::{Error, MapAccess, Visitor};
use serde::{Deserialize, Deserializer, Serialize};

use crate::arrays::*;
use crate::choices::*;
use cbor_derive::StructToMap;
use common::arrays::*;
use common::choices::*;
use common::*;
use serde::ser::Error as OtherError;

/// The `conditions` map used in `attest-key-triple-record` and `identity-triple-record`,
/// defined in [CoRIM Section 5.1.10].
///
/// ```text
/// conditions = non-empty<{
///   ? &(mkey: 0) => $measured-element-type-choice,
///   ? &(authorized-by: 1) => [ + $crypto-key-type-choice ]
/// }>
/// ```
///
/// [CoRIM Section 5.1.10]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.10
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[cbor(non_empty = "true")]
#[allow(missing_docs)]
pub struct AttestKeyConditionsMap {
    #[cbor(tag = "0", cbor = "true")]
    pub mkey: Option<MeasuredElementTypeChoice>,
    #[cbor(tag = "1", value = "Array")]
    pub authorized_by: Option<Vec<CryptoKeyTypeChoice>>,
}

/// The `class-map` type is defined in [CoRIM Section 5.1.4.2].
///
/// ```text
/// class-map = non-empty<{
///   ? &(class-id: 0) => $class-id-type-choice
///   ? &(vendor: 1) => tstr
///   ? &(model: 2) => tstr
///   ? &(layer: 3) => uint
///   ? &(index: 4) => uint
/// }>
/// ```
///
/// [CoRIM Section 5.1.4.2]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.4.2
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[cbor(non_empty = "true")]
#[allow(missing_docs)]
pub struct ClassMap {
    #[cbor(tag = "0", cbor = "true")]
    pub id: Option<ClassIdTypeChoice>,
    #[cbor(tag = "1", value = "Text")]
    pub vendor: Option<String>,
    #[cbor(tag = "2", value = "Text")]
    pub model: Option<String>,
    #[cbor(tag = "3", value = "Integer")]
    pub layer: Option<u128>,
    #[cbor(tag = "4", value = "Integer")]
    pub index: Option<u128>,
}

/// The `concise-mid-tag` type is defined in [CoRIM Section 5.1].
///
/// ```text
/// concise-mid-tag = {
///   ? &(language: 0) => text
///   &(tag-identity: 1) => tag-identity-map
///   ? &(entities: 2) => [ + comid-entity-map ]
///   ? &(linked-tags: 3) => [ + linked-tag-map ]
///   &(triples: 4) => triples-map
///   * $$concise-mid-tag-extension
/// }
/// ```
///
/// [CoRIM Section 5.1]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct ConciseMidTag {
    #[cbor(tag = "0", value = "Text")]
    pub language: Option<String>,
    #[cbor(tag = "1", value = "Map", cbor = "true")]
    #[serde(rename = "tag-identity")]
    pub tag_identity: Option<TagIdentityMap>,
    #[cbor(tag = "2", value = "Array", cbor = "true")]
    pub entities: Option<Vec<EntityMap>>,
    #[cbor(tag = "3", value = "Array", cbor = "true")]
    pub linked_tags: Option<Vec<LinkedTagMap>>,
    #[cbor(tag = "4", value = "Map", cbor = "true")]
    pub triples: TriplesMap,
    #[cbor(value = "Array", cbor = "true")]
    pub other: Option<Vec<Tuple>>,
}

/// The `corim-locator-map` type is defined in [CoRIM Section 4.1.3].
///
/// ```text
/// corim-locator-map = {
///   &(href: 0) => uri / [ + uri ]
///   ? &(thumbprint: 1) => eatmc.digest / [ eatmc.digest ]
/// }
/// ```
///
/// [CoRIM Section 4.1.3]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-4.1.3
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct CorimLocatorMap {
    //todo is taggeduri right?
    #[cbor(tag = "0", cbor = "true")]
    pub href: TaggedUriType,
    #[cbor(tag = "1", cbor = "true")]
    pub thumbprint: Option<HashEntry>,
}

/// The `corim-map` type is defined in [CoRIM Section 4.1].
///
/// ```text
/// corim-map = {
///   &(id: 0) => $corim-id-type-choice
///   &(tags: 1) => [ + $concise-tag-type-choice ]
///   ? &(dependent-rims: 2) => [ + corim-locator-map ]
///   ? &(profile: 3) => $profile-type-choice
///   ? &(rim-validity: 4) => validity-map
///   ? &(entities: 5) => [ + corim-entity-map ]
///   * $$corim-map-extension
/// }
/// ```
///
/// [CoRIM Section 4.1]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-4.1
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct CorimMap {
    #[cbor(tag = "0")]
    pub id: CorimIdTypeChoice,
    #[cbor(tag = "1", value = "Array")]
    pub tags: Vec<ConciseTagTypeChoice>,
    #[cbor(tag = "2", value = "Array", cbor = "true")]
    pub dependent_rims: Option<Vec<CorimLocatorMap>>,
    #[cbor(tag = "3", cbor = "true")]
    pub profile: Option<ProfileTypeChoice>,
    #[cbor(tag = "4", value = "Map", cbor = "true")]
    pub rim_validity: Option<ValidityMap>,
    #[cbor(tag = "5", value = "Array", cbor = "true")]
    pub entities: Option<Vec<EntityMap>>,
}

/// The `corim-meta-map` type is defined in [CoRIM Section 4.2.3].
///
/// ```text
/// corim-meta-map = {
///   &(signer: 0) => corim-signer-map
///   ? &(signature-validity: 1) => validity-map
/// }
/// ```
///
/// [CoRIM Section 4.2.3]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-4.2.3
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct CorimMetaMap {
    #[cbor(tag = "0", value = "Map", cbor = "true")]
    pub signer: CorimSignerMap,
    #[cbor(tag = "1", value = "Map", cbor = "true")]
    pub validity: Option<ValidityMap>,
}

/// The `corim-signer-map` type is defined in [CoRIM Section 4.2.3.1].
///
/// ```text
/// corim-signer-map = {
///   &(signer-name: 0) => $entity-name-type-choice
///   ? &(signer-uri: 1) => uri
///   * $$corim-signer-map-extension
/// }
/// ```
///
/// [CoRIM Section 4.2.3.1]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-4.2.3.1
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct CorimSignerMap {
    #[cbor(tag = "0")]
    pub entity_name: EntityNameTypeChoice,
    #[cbor(tag = "1", cbor = "true")]
    pub reg_id: Option<TaggedUriType>,
    //todo extensibility
    //extensions
}

/// The `entity-map` type is defined in [CoRIM Section 7.2].
///
/// [CoRIM Section 7.2]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-7.2
///
/// ```text
/// entity-map<role, extension> = {
///   &(entity-name: 31) => $entity-name-type-choice
///   ? &(reg-id: 32) => uri
///   &(role: 33) => [ + role-type-choice ]
///   * extension
/// }
/// ```
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct EntityMap {
    #[cbor(tag = "31")]
    pub name: EntityNameTypeChoice,
    #[cbor(tag = "32", cbor = "true")]
    pub regid: Option<TaggedUriType>,
    #[cbor(tag = "33", value = "Array", cbor = "true")]
    pub roles: Vec<CorimRoleTypeChoice>,
}

/// The `corim-entity-map` instantiation of [`EntityMap`].
///
/// ```text
/// corim-entity-map = entity-map<$corim-role-type-choice,
///                               $$corim-entity-map-extension>
/// ```
///
/// See [CoRIM Section 4.1.4].
///
/// [CoRIM Section 4.1.4]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-4.1.4
pub type CorimEntityMap = EntityMap;

/// CBOR-encoded form of [`CorimEntityMap`].
pub type CorimEntityMapCbor = EntityMapCbor;

/// The `comid-entity-map` instantiation of [`EntityMap`].
///
/// ```text
/// comid-entity-map = entity-map<$comid-role-type-choice,
///                               $$comid-entity-map-extension>
/// ```
///
/// See [CoRIM Section 5.1.3].
///
/// [CoRIM Section 5.1.3]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.3
pub type ComidEntityMap = EntityMap;

/// CBOR-encoded form of [`ComidEntityMap`].
pub type ComidEntityMapCbor = EntityMapCbor;

/// The `environment-map` type is defined in [CoRIM Section 5.1.4.1].
///
/// ```text
/// environment-map = non-empty<{
///   ? &(class: 0) => class-map
///   ? &(instance: 1) => $instance-id-type-choice
///   ? &(group: 2) => $group-id-type-choice
/// }>
/// ```
///
/// [CoRIM Section 5.1.4.1]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.4.1
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[cbor(non_empty = "true")]
#[allow(missing_docs)]
pub struct EnvironmentMap {
    #[cbor(tag = "0", cbor = "true")]
    pub class: Option<ClassMap>,
    #[cbor(tag = "1")]
    pub instance: Option<InstanceIdTypeChoice>,
    #[cbor(tag = "2")]
    pub group: Option<GroupIdTypeChoice>,
    //todo extensibility
    //extensions
}

/// The `flags-map` type is defined in [CoRIM Section 5.1.4.5.5].
///
/// [CoRIM Section 5.1.4.5.5]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.4.5.5
///
/// ```text
///   flags-map = {
///      ? &(is-configured: 0) => bool
///      ? &(is-secure: 1) => bool
///      ? &(is-recovery: 2) => bool
///      ? &(is-debug: 3) => bool
///      ? &(is-replay-protected: 4) => bool
///      ? &(is-integrity-protected: 5) => bool
///      ? &(is-runtime-meas: 6) => bool
///      ? &(is-immutable: 7) => bool
///      ? &(is-tcb: 8) => bool
///      ? &(is-confidentiality-protected: 9) => bool
///      * $$flags-map-extension
///    }
/// ```
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct FlagsMap {
    #[cbor(tag = "0", value = "Bool")]
    pub is_configured: Option<bool>,
    #[cbor(tag = "1", value = "Bool")]
    pub is_secure: Option<bool>,
    #[cbor(tag = "2", value = "Bool")]
    pub is_recovery: Option<bool>,
    #[cbor(tag = "3", value = "Bool")]
    pub is_debug: Option<bool>,
    #[cbor(tag = "4", value = "Bool")]
    pub is_replay_protected: Option<bool>,
    #[cbor(tag = "5", value = "Bool")]
    pub is_integrity_protected: Option<bool>,
    #[cbor(tag = "6", value = "Bool")]
    pub is_runtime_meas: Option<bool>,
    #[cbor(tag = "7", value = "Bool")]
    pub is_immutable: Option<bool>,
    #[cbor(tag = "8", value = "Bool")]
    pub is_tcb: Option<bool>,
    #[cbor(tag = "9", value = "Bool")]
    pub is_confidentiality_protected: Option<bool>,
}

/// The `linked-tag-map` type is defined in [CoRIM Section 5.1.3].
///
/// ```text
/// linked-tag-map = {
///   &(linked-tag-id: 0) => $tag-id-type-choice
///   &(tag-rel: 1) => $tag-rel-type-choice
/// }
/// ```
///
/// [CoRIM Section 5.1.3]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.3
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct LinkedTagMap {
    #[cbor(tag = "0", cbor = "true")]
    pub linked_tag_id: TagIdTypeChoice,
    #[cbor(tag = "1")]
    pub tag_rel: TagRelTypeChoice,
}

/// The `measurement-map` type is defined in [CoRIM Section 5.1.4.5].
///
/// [CoRIM Section 5.1.4.5]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.4.5
///
/// ```text
/// measurement-map = {
///   ? &(mkey: 0) => $measured-element-type-choice
///   &(mval: 1) => measurement-values-map
///   ? &(authorized-by: 2) => [ + $crypto-key-type-choice ]
/// }
/// ```
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct MeasurementMap {
    #[cbor(tag = "0", cbor = "true")]
    pub mkey: Option<MeasuredElementTypeChoice>,
    #[cbor(tag = "1", value = "Map", cbor = "true")]
    pub value: MeasurementValuesMap,
    #[cbor(tag = "2", value = "Array", cbor = "true")]
    pub authorized_by: Option<Vec<CryptoKeyTypeChoice>>,
}

/// The `measurement-values-map` type is defined in [CoRIM Section 5.1.4.5.2].
///
/// [CoRIM Section 5.1.4.5.2]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.4.5.2
///
/// ```text
/// measurement-values-map = non-empty<{
///   ? &(version: 0) => version-map
///   ? &(svn: 1) => svn-type-choice
///   ? &(digests: 2) => digests-type
///   ? &(flags: 3) => flags-map
///   ? &(raw-value: 4) => $raw-value-type-choice
///   ? &(raw-value-mask: 5) => raw-value-mask-type  ; deprecated
///   ? &(mac-addr: 6) => mac-addr-type-choice
///   ? &(ip-addr: 7) => ip-addr-type-choice
///   ? &(serial-number: 8) => text
///   ? &(ueid: 9) => ueid-type
///   ? &(uuid: 10) => uuid-type
///   ? &(name: 11) => text
///   ? &(cryptokeys: 13) => [ + $crypto-key-type-choice ]
///   ? &(integrity-registers: 14) => integrity-registers
///   ? &(int-range: 15) => $int-range-type-choice
///   * $$measurement-values-map-extension
/// }>
/// ```
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[cbor(non_empty = "true")]
#[allow(missing_docs)]
pub struct MeasurementValuesMap {
    #[cbor(tag = "0", value = "Map", cbor = "true")]
    pub version: Option<VersionMap>,
    #[cbor(tag = "1")]
    pub svn: Option<SvnTypeChoice>,
    #[cbor(tag = "2", value = "Array", cbor = "true")]
    pub digests: Option<Vec<HashEntry>>,
    #[cbor(tag = "3", value = "Map", cbor = "true")]
    #[serde(rename = "op-flags")]
    pub flags: Option<FlagsMap>,
    #[cbor(tag = "4")]
    pub raw_value: Option<RawValueTypeChoice>,
    #[cbor(tag = "5", value = "Bytes")]
    pub raw_value_mask: Option<Vec<u8>>,
    #[cbor(tag = "6", value = "Bytes")]
    pub mac_addr: Option<Vec<u8>>,
    #[cbor(tag = "7", value = "Bytes")]
    pub ip_addr: Option<Vec<u8>>,
    #[cbor(tag = "8", value = "Text")]
    pub serial_number: Option<String>,
    #[cbor(tag = "9")]
    pub ueid: Option<UeidType>,
    #[cbor(tag = "10")]
    pub uuid: Option<UuidType>,
    #[cbor(tag = "11", value = "Text")]
    pub name: Option<String>,
    #[cbor(tag = "13", value = "Array", cbor = "true")]
    pub cryptokeys: Option<Vec<CryptoKeyTypeChoice>>,
    // #[cbor(tag = "14", value = "Map")]
    // pub integrity_registers: Option<IntegrityRegisters>,
    #[cbor(tag = "15")]
    pub int_range: Option<IntRangeTypeChoice>,
    #[cbor(value = "Array", cbor = "true")]
    pub other: Option<Vec<Tuple>>,
}

/// The `protected-corim-header-map` type is defined in [CoRIM Section 4.2.1].
///
/// [CoRIM Section 4.2.1]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-4.2.1
///
/// ```text
/// protected-corim-header-map-inline = {
///   &(alg: 1) => int
///   &(content-type: 3) => "application/rim+cbor"
///   meta-group
///   * cose-label => cose-value
/// }
/// ```
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct ProtectedCorimHeaderMap {
    #[cbor(tag = "0", value = "Integer")]
    pub alg_id: u64,
    #[cbor(tag = "3", value = "Text")]
    content_type: String,
    #[cbor(tag = "8", value = "Map", cbor = "true")]
    pub meta: CorimMetaMap,
}

/// The `tag-identity-map` type is defined in [CoRIM Section 5.1.1].
///
/// ```text
/// tag-identity-map = {
///   &(tag-id: 0) => $tag-id-type-choice
///   ? &(tag-version: 1) => tag-version-type
/// }
/// ```
///
/// [CoRIM Section 5.1.1]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.1
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct TagIdentityMap {
    #[cbor(tag = "0", cbor = "true")]
    #[serde(rename = "id")]
    pub tag_id: TagIdTypeChoice,
    #[cbor(tag = "1")]
    #[serde(rename = "version", default)]
    pub tag_version: Option<TagVersionType>,
}

impl TagIdentityMap {
    /// Returns the tag version, defaulting to 0 when absent per the CDDL
    /// `.default 0` constraint.
    pub fn tag_version_or_default(&self) -> u64 {
        match &self.tag_version {
            Some(TagVersionType::U64(v)) => *v,
            None => 0,
        }
    }
}

/// The `triples-map` type is defined in [CoRIM Section 5.1.4].
///
/// [CoRIM Section 5.1.4]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.4
///
/// ```text
/// triples-map = non-empty<{
///   ? &(reference-triples: 0) => [ + reference-triple-record ]
///   ? &(endorsed-triples: 1)  => [ + endorsed-triple-record ]
///   ? &(identity-triples: 2) => [ + identity-triple-record ]
///   ? &(attest-key-triples: 3) => [ + attest-key-triple-record ]
///   ? &(dependency-triples: 4) => [ + domain-dependency-triple-record ]
///   ? &(membership-triples: 5) => [ + domain-membership-triple-record ]
///   ? &(coswid-triples: 6) => [ + coswid-triple-record ]
///   ? &(conditional-endorsement-series-triples: 8) => [ + conditional-endorsement-series-triple-record ]
///   ? &(conditional-endorsement-triples: 10) => [ + conditional-endorsement-triple-record ]
///   * $$triples-map-extension
/// }>
/// ```
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[cbor(non_empty = "true")]
#[allow(missing_docs)]
pub struct TriplesMap {
    #[cbor(tag = "0", value = "Array", cbor = "true")]
    #[serde(rename = "reference-values")]
    pub reference_triples: Option<Vec<ReferenceTripleRecord>>,
    #[cbor(tag = "1", value = "Array", cbor = "true")]
    pub endorsed_triples: Option<Vec<EndorsedTripleRecord>>,
    #[cbor(tag = "2", value = "Array", cbor = "true")]
    pub identity_triples: Option<Vec<IdentityTripleRecord>>,
    #[cbor(tag = "3", value = "Array", cbor = "true")]
    pub attest_key_triples: Option<Vec<AttestKeyTripleRecord>>,
    #[cbor(tag = "4", value = "Array", cbor = "true")]
    pub dependency_triples: Option<Vec<DomainDependencyTripleRecord>>,
    #[cbor(tag = "5", value = "Array", cbor = "true")]
    pub membership_triples: Option<Vec<DomainMembershipTripleRecord>>,
    #[cbor(tag = "6", value = "Array", cbor = "true")]
    pub coswid_triples: Option<Vec<CoswidTripleRecord>>,
    #[cbor(tag = "8", value = "Array", cbor = "true")]
    pub conditional_endorsement_series_triples:
        Option<Vec<ConditionalEndorsementSeriesTripleRecord>>,
    #[cbor(tag = "10", value = "Array", cbor = "true")]
    pub conditional_endorsement_triples: Option<Vec<ConditionalEndorsementTripleRecord>>,
    #[cbor(value = "Array", cbor = "true")]
    pub other: Option<Vec<Tuple>>,
}

/// The `validity-map` type is defined in [CoRIM Section 7.3].
///
/// [CoRIM Section 7.3]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-7.3
///
/// ```text
/// validity-map = {
///   ? &(not-before: 0) => time
///   ? &(not-after: 1) => time
/// }
/// ```
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct ValidityMap {
    #[cbor(tag = "0", cbor = "true")]
    pub not_before: Option<Time>,
    #[cbor(tag = "1", cbor = "true")]
    pub not_after: Option<Time>,
}

/// The `version-map` type is defined in [CoRIM Section 5.1.4.5.3].
///
/// ```text
/// version-type = text .default '0.0.0'
/// version-map = {
///   &(version: 0) => text
///   ? &(version-scheme: 1) => $version-scheme
/// }
/// ```
///
/// [CoRIM Section 5.1.4.5.3]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-5.1.4.5.3
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct VersionMap {
    #[cbor(tag = "0", value = "Text")]
    pub version: String,
    #[cbor(tag = "1")]
    pub version_scheme: Option<VersionScheme>,
}

/// The `concise-tl-tag` type is defined in [CoRIM Section 6.1].
///
/// [CoRIM Section 6.1]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-corim-10#section-6.1
///
/// ```text
/// concise-tl-tag = {
///   &(tl-tag-id: 0) => $tag-id-type-choice
///   ? &(tl-tag-version: 1) => uint
///   &(tl-corim-ids: 2) => [ + $corim-id-type-choice ]
/// }
/// ```
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct ConciseTlTag {
    #[cbor(tag = "0", cbor = "true")]
    pub tag_id: TagIdTypeChoice,
    #[cbor(tag = "1", value = "Integer")]
    pub tag_version: Option<u64>,
    #[cbor(tag = "2", value = "Array")]
    pub corim_ids: Vec<CorimIdTypeChoice>,
}
