//! Map-based structs from the Concise Trust Anchor Store (CoTS) spec
//! ([draft-ietf-rats-concise-ta-stores]).
//!
//! This module implements the following CDDL productions:
//!
//! | CDDL | Rust |
//! |------|------|
//! | `abbreviated-swid-tag` | [`AbbreviatedSwidTag`] / [`AbbreviatedSwidTagCbor`] |
//! | `cas-and-tas-map` | [`CasAndTasMap`] / [`CasAndTasMapCbor`] |
//! | `concise-ta-store-map` | [`ConciseTaStoreMap`] / [`ConciseTaStoreMapCbor`] |
//! | `environment-group-list-map` | [`EnvironmentGroupListMap`] / [`EnvironmentGroupListMapCbor`] |
//!
//! Each struct has a companion `*Cbor` type generated by the
//! [`StructToMap`] macro for direct CBOR map serialization.
//!
//! [draft-ietf-rats-concise-ta-stores]: https://datatracker.ietf.org/doc/html/draft-ietf-rats-concise-ta-stores

use ciborium::{cbor, value::Value};
use core::{fmt, marker::PhantomData};
use serde::de::{Error, MapAccess, Visitor};
use serde::{Deserialize, Deserializer, Serialize};

use alloc::collections::BTreeMap;
use alloc::format;
use alloc::string::{String, ToString};
use alloc::{vec, vec::Vec};

use crate::arrays::*;
use crate::choices::TasListPurpose;
use cbor_derive::StructToMap;
use common::choices::*;
use common::*;
use corim::choices::TagVersionType;
use corim::maps::*;
use coswid::maps::*;
use eat::maps::ClaimsSetClaims;
use eat::maps::*;
use serde::ser::Error as OtherError;

/// ```text
/// abbreviated-swid-tag = {
///   ? tag-version => integer,
///   ? corpus => bool,
///   ? patch => bool,
///   ? supplemental => bool,
///   ? software-name => text,
///   ? software-version => text,
///   ? version-scheme => $version-scheme,
///   ? media => text,
///   ? software-meta => one-or-more<software-meta-entry>,
///   ? entity => one-or-more<entity-entry>,
///   ? link => one-or-more<link-entry>,
///   ? payload-or-evidence,
///   * $$coswid-extension,
///   global-attributes,
/// }
/// ```
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct AbbreviatedSwidTag {
    #[cbor(tag = "12")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag_version: Option<TagVersionType>,
    #[cbor(tag = "8", value = "Bool")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub corpus: Option<bool>,
    #[cbor(tag = "9", value = "Bool")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub patch: Option<bool>,
    #[cbor(tag = "11", value = "Bool")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub supplemental: Option<bool>,
    #[cbor(tag = "1", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub software_name: Option<String>,
    #[cbor(tag = "13", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub software_version: Option<String>,
    #[cbor(tag = "14")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version_scheme: Option<VersionScheme>,
    #[cbor(tag = "10", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media: Option<String>,
    #[cbor(tag = "5", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub software_meta: Option<OneOrMoreSoftwareMetaEntry>,
    #[cbor(tag = "2", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entity: Option<OneOrMoreEntityEntry>,
    #[cbor(tag = "4", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub link: Option<OneOrMoreLinkEntry>,
    #[cbor(tag = "3", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub evidence: Option<EvidenceEntry>,
    #[cbor(tag = "6", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<PayloadEntry>,
    //* $$coswid-extension,
    #[cbor(tag = "15", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    //global-attributes,
    // todo extensions and attributes
}

// ; cas-and-tas-map indices
// tastore.tas = 0
// tastore.cas = 1
// cas-and-tas-map = {
//  tastore.tas => [ + trust-anchor ]
//  ? tastore.cas => [ + tastore.pkix-cert-type ]
// }
/// Represents the `cas-and-tas-map` from the CoTS specification.
///
/// Contains required trust anchors and optional CA certificates for a Concise TA Store entry.
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct CasAndTasMap {
    #[cbor(tag = "0", value = "Array", cbor = "true")]
    pub tas: Vec<TrustAnchor>,
    #[cbor(tag = "1", value = "Array")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cas: Option<Vec<PkixCa>>,
}

// ; concise-ta-store-map indices
// tastore.language = 0
// tastore.store-identity = 1
// tastore.environment = 2
// tastore.purpose = 3
// tastore.perm_claims = 4
// tastore.excl_claims = 5
// tastore.keys = 6
// concise-ta-store-map = {
//  ? tastore.language => language-type
//  ? tastore.store-identity => tag-identity-map
//  tastore.environments => environment-group-list
//  ? tastore.purposes => [+ $$tas-list-purpose]
//  ? tastore.perm_claims => [+ $$claims-set-claims]
//  ? tastore.excl_claims => [+ $$claims-set-claims]
//  tastore.keys => cas-and-tas-map
// }
/// Represents the `concise-ta-store-map` from the CoTS specification.
///
/// Defines a trust anchor store entry with environments, purposes, permitted/excluded claims, and keys.
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct ConciseTaStoreMap {
    #[cbor(tag = "0", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[cbor(tag = "1", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub store_identity: Option<TagIdentityMap>,
    #[cbor(tag = "2", cbor = "true")]
    pub environments: EnvironmentGroupList,
    #[cbor(tag = "3", value = "Array")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub purposes: Option<Vec<TasListPurpose>>,
    #[cbor(tag = "4", value = "Array", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub perm_claims: Option<Vec<ClaimsSetClaims>>,
    #[cbor(tag = "5", value = "Array", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub excl_claims: Option<Vec<ClaimsSetClaims>>,
    #[cbor(tag = "6", cbor = "true")]
    pub keys: CasAndTasMap,
}

/// Represents the `environment-group-list-map` from the CoTS specification.
///
/// ```text
/// environment-group-list-map = {
///   ? environment-map => environment-map,
///   ? concise-swid-tag => abbreviated-swid-tag,
///   ? named-ta-store => named-ta-store,
/// }
/// ```
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct EnvironmentGroupListMap {
    #[cbor(tag = "1", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub environment_map: Option<EnvironmentMap>,
    #[cbor(tag = "2", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub concise_swid_tag: Option<AbbreviatedSwidTag>,
    #[cbor(tag = "3", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub named_ta_store: Option<String>,
}
