[package]
name = "webauthn_asf"
description = "CBOR-focused encoders/decoders for WebAuthn attestation statement formats"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/carl-wallace/cbor-formats/tree/main/webauthn_asf"
categories = ["cryptography", "data-structures", "encoding", "no-std", "parser-implementations"]
keywords = ["cbor", "webauthn", "attestation", "fido"]
readme = "README.md"
version = "0.1.1"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
cbor_derive = { version = "0.1.1", path = "../cbor_derive" }
common = { version = "0.1.1", path = "../common" }
ciborium = "0.2.2"
subtle-encoding = {version = "0.5.1", default-features = false, features = ["hex", "alloc"]}
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
hex-literal = "1.1.0"
serde_bytes = "0.11"
serde_json = "1.0.149"
