//! Map-based structs from the Concise Software Identification Tags (CoSWID) spec ([RFC 9393]).
//!
//! This module implements the following CDDL productions:
//!
//! | CDDL | Rust |
//! |------|------|
//! | `concise-swid-tag` | [`ConciseSwidTag`] / [`ConciseSwidTagCbor`] |
//! | `entity-entry` | [`EntityEntry`] / [`EntityEntryCbor`] |
//! | `file-entry` | [`FileEntry`] / [`FileEntryCbor`] |
//! | `directory-entry` | [`DirectoryEntry`] / [`DirectoryEntryCbor`] |
//! | `link-entry` | [`LinkEntry`] / [`LinkEntryCbor`] |
//! | `payload-entry` | [`PayloadEntry`] / [`PayloadEntryCbor`] |
//! | `evidence-entry` | [`EvidenceEntry`] / [`EvidenceEntryCbor`] |
//! | `process-entry` | [`ProcessEntry`] / [`ProcessEntryCbor`] |
//! | `resource-entry` | [`ResourceEntry`] / [`ResourceEntryCbor`] |
//! | `software-meta-entry` | [`SoftwareMetaEntry`] / [`SoftwareMetaEntryCbor`] |
//! | `path-elements-group` | [`PathElementsGroup`] / [`PathElementsGroupCbor`] |
//! | `resource-collection` | [`ResourceCollection`] / [`ResourceCollectionCbor`] |
//!
//! Each struct has a companion `*Cbor` type generated by the
//! [`StructToMap`] macro for direct CBOR map serialization.
//!
//! [RFC 9393]: https://datatracker.ietf.org/doc/html/rfc9393

use alloc::{
    collections::BTreeMap,
    format,
    string::{String, ToString},
    vec,
    vec::Vec,
};
use core::{fmt, marker::PhantomData};

use ciborium::{cbor, value::Value};
use serde::{
    Deserialize, Deserializer, Serialize,
    de::{Error, MapAccess, Visitor},
    ser::Error as OtherError,
};

use cbor_derive::{StructToMap, StructToOneOrMore};
use common::{arrays::*, choices::*, *};

use crate::choices::*;

// ; concise-swig-tag map indices (culled from global map member)
// tag-id = 0
// tag-version = 12
// corpus = 8
// patch = 9
// supplemental = 11
// software-name = 1
// software-version = 13
// version-scheme = 14
// media = 10
// software-meta = 5
// entity = 2
// link = 4
// evidence = 3
// payload = 6

/// The `concise-swid-tag` type is defined in [CoSWID Section 2.3].
///
/// ```text
/// concise-swid-tag = {
///   tag-id => text / bstr .size 16,
///   tag-version => integer,
///   ? corpus => bool,
///   ? patch => bool,
///   ? supplemental => bool,
///   software-name => text,
///   ? software-version => text,
///   ? version-scheme => $version-scheme,
///   ? media => text,
///   ? software-meta => one-or-more<software-meta-entry>,
///   entity => one-or-more<entity-entry>,
///   ? link => one-or-more<link-entry>,
///   ? payload-or-evidence,
///   * $$coswid-extension,
///   global-attributes,
/// }
/// ```
///
/// [CoSWID Section 2.3]: https://datatracker.ietf.org/doc/html/rfc9393#section-2.3
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct ConciseSwidTag {
    #[cbor(tag = "0")]
    pub tag_id: TextOrBinary,
    #[cbor(tag = "12", value = "Integer")]
    pub tag_version: i64,
    #[cbor(tag = "8", value = "Bool")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub corpus: Option<bool>,
    #[cbor(tag = "9", value = "Bool")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub patch: Option<bool>,
    #[cbor(tag = "11", value = "Bool")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub supplemental: Option<bool>,
    #[cbor(tag = "1", value = "Text")]
    pub software_name: String,
    #[cbor(tag = "13", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub software_version: Option<String>,
    #[cbor(tag = "14", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version_scheme: Option<VersionScheme>,
    #[cbor(tag = "10", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media: Option<String>,
    #[cbor(tag = "5", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub software_meta: Option<OneOrMoreSoftwareMetaEntry>,
    #[cbor(tag = "2", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entity: Option<OneOrMoreEntityEntry>,
    #[cbor(tag = "4", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub link: Option<OneOrMoreLinkEntry>,
    #[cbor(tag = "3", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub evidence: Option<EvidenceEntry>,
    #[cbor(tag = "6", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<PayloadEntry>,
    //* $$coswid-extension,
    #[cbor(tag = "15", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    //global-attributes,
    #[cbor(value = "Array", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub other: Option<Vec<Tuple>>,
}

// directory-entry = {
//    ? key => bool,
//    ? location => text,
//    fs-name => text,
//    ? root => text,
//   ? path-elements => { path-elements-group },
//   * $$directory-extension,
//   ? lang => text,
//   global-attributes,
// }

/// The `directory-entry` type is defined in [CoSWID Section 2.9.2].
///
/// ```text
/// directory-entry = {
///   filesystem-item,
///   ? path-elements => { path-elements-group },
///   * $$directory-extension,
///   global-attributes,
/// }
/// ```
///
/// [CoSWID Section 2.9.2]: https://datatracker.ietf.org/doc/html/rfc9393#section-2.9.2
#[derive(Clone, Debug, PartialEq, StructToMap, StructToOneOrMore, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct DirectoryEntry {
    #[cbor(tag = "22", value = "Bool")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key: Option<bool>,
    #[cbor(tag = "23", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[cbor(tag = "24", value = "Text")]
    pub fs_name: String,
    #[cbor(tag = "25", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub root: Option<String>,
    //todo handle recursion via Box
    // #[cbor(tag = "26", value = "Text")]
    // pub path_elements: Option<Box<PathElementsGroup>>,
    //   * $$directory-extension,
    #[cbor(tag = "15", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    //   global-attributes,
    #[cbor(value = "Array", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub other: Option<Vec<Tuple>>,
}

/// The `entity-entry` type is defined in [CoSWID Section 2.6].
///
/// ```text
/// entity-entry = {
///   entity-name => text,
///   ? reg-id => any-uri,
///   role => one-or-more<$role>,
///   ? thumbprint => hash-entry,
///   * $$entity-extension,
///   global-attributes,
/// }
/// ```
///
/// [CoSWID Section 2.6]: https://datatracker.ietf.org/doc/html/rfc9393#section-2.6
#[derive(Clone, Debug, PartialEq, StructToMap, StructToOneOrMore, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct EntityEntry {
    #[cbor(tag = "31", value = "Text")]
    pub entity_name: String,
    #[cbor(tag = "32", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reg_id: Option<Uri>,
    #[cbor(tag = "33")]
    pub role: OneOrMoreRole,
    #[cbor(tag = "34", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thumbprint: Option<HashEntry>,
    //   * $$entity-extension,
    #[cbor(tag = "15", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    //   global-attributes,
    #[cbor(value = "Array", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub other: Option<Vec<Tuple>>,
}

/// The `evidence-entry` type is defined in [CoSWID Section 2.9.4].
///
/// ```text
/// evidence-entry = {
///   resource-collection,
///   ? date => integer-time,
///   ? device-id => text,
///   ? location => text,
///   * $$evidence-extension,
///   global-attributes,
/// }
/// ```
///
/// [CoSWID Section 2.9.4]: https://datatracker.ietf.org/doc/html/rfc9393#section-2.9.4
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct EvidenceEntry {
    #[cbor(tag = "16", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub directory: Option<OneOrMoreDirectoryEntry>,
    #[cbor(tag = "17", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file: Option<OneOrMoreFileEntry>,
    #[cbor(tag = "18", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub process: Option<OneOrMoreProcessEntry>,
    #[cbor(tag = "19", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resource: Option<OneOrMoreResourceEntry>,
    #[cbor(tag = "35", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub date: Option<Time>,
    #[cbor(tag = "36", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_id: Option<String>,
    #[cbor(tag = "23", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    //   * $$evidence-extension,
    #[cbor(tag = "15", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    //   global-attributes,
    #[cbor(value = "Array", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub other: Option<Vec<Tuple>>,
}

/// The `file-entry` type is defined in [CoSWID Section 2.9.2].
///
/// ```text
/// file-entry = {
///   filesystem-item,
///   ? size => uint,
///   ? file-version => text,
///   ? hash => hash-entry,
///   * $$file-extension,
///   global-attributes,
/// }
/// ```
///
/// [CoSWID Section 2.9.2]: https://datatracker.ietf.org/doc/html/rfc9393#section-2.9.2
#[derive(Clone, Debug, PartialEq, StructToMap, StructToOneOrMore, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct FileEntry {
    #[cbor(tag = "22", value = "Bool")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key: Option<bool>,
    #[cbor(tag = "23", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[cbor(tag = "24", value = "Text")]
    pub fs_name: String,
    #[cbor(tag = "25", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub root: Option<String>,
    #[cbor(tag = "20", value = "Integer")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    #[cbor(tag = "21", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_version: Option<String>,
    #[cbor(tag = "7", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hash: Option<HashEntry>,
    //   * $$file-extension,
    #[cbor(tag = "15", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    //   global-attributes,
    #[cbor(value = "Array", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub other: Option<Vec<Tuple>>,
}

/// The `link-entry` type is defined in [CoSWID Section 2.7].
///
/// ```text
/// link-entry = {
///   ? artifact => text,
///   href => any-uri,
///   ? media => text,
///   ? ownership => $ownership,
///   rel => $rel,
///   ? media-type => text,
///   ? use => $use,
///   * $$link-extension,
///   global-attributes,
/// }
/// ```
///
/// [CoSWID Section 2.7]: https://datatracker.ietf.org/doc/html/rfc9393#section-2.7
#[derive(Clone, Debug, PartialEq, StructToMap, StructToOneOrMore, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct LinkEntry {
    #[cbor(tag = "37", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub artifact: Option<String>,
    #[cbor(tag = "38", value = "Text")]
    pub href: Uri,
    #[cbor(tag = "10", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media: Option<String>,
    #[cbor(tag = "39")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ownership: Option<Ownership>,
    #[cbor(tag = "40")]
    pub rel: Rel,
    #[cbor(tag = "41", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_type: Option<String>,
    #[cbor(tag = "42")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub use_choice: Option<UseChoice>,
    //   * $$link-extension,
    #[cbor(tag = "15", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    //   global-attributes,
    #[cbor(value = "Array", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub other: Option<Vec<Tuple>>,
}

/// The `path-elements-group` type is defined in [CoSWID Section 2.9.2].
///
/// ```text
/// { path-elements-group }
/// path-elements-group = ( ? directory => one-or-more<directory-entry>,
///                         ? file => one-or-more<file-entry>,
///                       )
/// ```
///
/// [CoSWID Section 2.9.2]: https://datatracker.ietf.org/doc/html/rfc9393#section-2.9.2
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct PathElementsGroup {
    #[cbor(tag = "16", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub directory: Option<OneOrMoreDirectoryEntry>,
    #[cbor(tag = "17", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file: Option<OneOrMoreFileEntry>,
}

/// The `resource-collection` group from [CoSWID Section 2.9.2].
///
/// This extends [`PathElementsGroup`] with `process` and `resource` fields.
///
/// ```text
/// resource-collection = (
///   path-elements-group,
///   ? process => one-or-more<process-entry>,
///   ? resource => one-or-more<resource-entry>,
///   * $$resource-collection-extension,
/// )
/// ```
///
/// Note: `resource-collection` is a CDDL group, so its fields are flattened
/// into the containing map (`payload-entry`, `evidence-entry`). This struct
/// provides a standalone representation of the group.
///
/// [CoSWID Section 2.9.2]: https://datatracker.ietf.org/doc/html/rfc9393#section-2.9.2
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct ResourceCollection {
    #[cbor(tag = "16", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub directory: Option<OneOrMoreDirectoryEntry>,
    #[cbor(tag = "17", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file: Option<OneOrMoreFileEntry>,
    #[cbor(tag = "18", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub process: Option<OneOrMoreProcessEntry>,
    #[cbor(tag = "19", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resource: Option<OneOrMoreResourceEntry>,
}

/// The `payload-entry` type is defined in [CoSWID Section 2.9.3].
///
/// ```text
/// payload-entry = {
///   resource-collection,
///   * $$payload-extension,
///   global-attributes,
/// }
/// ```
///
/// [CoSWID Section 2.9.3]: https://datatracker.ietf.org/doc/html/rfc9393#section-2.9.3
#[derive(Clone, Debug, PartialEq, StructToMap, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct PayloadEntry {
    #[cbor(tag = "16", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub directory: Option<OneOrMoreDirectoryEntry>,
    #[cbor(tag = "17", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file: Option<OneOrMoreFileEntry>,
    #[cbor(tag = "18", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub process: Option<OneOrMoreProcessEntry>,
    #[cbor(tag = "19", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resource: Option<OneOrMoreResourceEntry>,
    //   * $$payload-extension,
    #[cbor(tag = "15", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    //   global-attributes,
    #[cbor(value = "Array", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub other: Option<Vec<Tuple>>,
}

/// The `process-entry` type is defined in [CoSWID Section 2.9.2].
///
/// ```text
/// process-entry = {
///   process-name => text,
///   ? pid => integer,
///   * $$process-extension,
///   global-attributes,
/// }
/// ```
///
/// [CoSWID Section 2.9.2]: https://datatracker.ietf.org/doc/html/rfc9393#section-2.9.2
#[derive(Clone, Debug, PartialEq, StructToMap, StructToOneOrMore, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct ProcessEntry {
    #[cbor(tag = "27", value = "Text")]
    pub process_name: String,
    #[cbor(tag = "28", value = "Integer")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pid: Option<i64>,
    //   * process-extension,
    #[cbor(tag = "15", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    //   global-attributes,
    #[cbor(value = "Array", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub other: Option<Vec<Tuple>>,
}

/// The `resource-entry` type is defined in [CoSWID Section 2.9.2].
///
/// ```text
/// resource-entry = {
///   type => text,
///   * $$resource-extension,
///   global-attributes,
/// }
/// ```
///
/// [CoSWID Section 2.9.2]: https://datatracker.ietf.org/doc/html/rfc9393#section-2.9.2
#[derive(Clone, Debug, PartialEq, StructToMap, StructToOneOrMore, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct ResourceEntry {
    #[cbor(tag = "29", value = "Text")]
    pub resource_entry_type: String,
    //   * $$resource-extension,
    #[cbor(tag = "15", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    //   global-attributes,
    #[cbor(value = "Array", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub other: Option<Vec<Tuple>>,
}

/// The `software-meta-entry` type is defined in [CoSWID Section 2.8].
///
/// ```text
/// software-meta-entry = {
///   ? activation-status => text,
///   ? channel-type => text,
///   ? colloquial-version => text,
///   ? description => text,
///   ? edition => text,
///   ? entitlement-data-required => bool,
///   ? entitlement-key => text,
///   ? generator => text,
///   ? persistent-id => text,
///   ? product => text,
///   ? product-family => text,
///   ? revision => text,
///   ? summary => text,
///   ? unspsc-code => text,
///   ? unspsc-version => text,
///   * $$software-meta-extension,
///   global-attributes,
/// }
/// ```
///
/// [CoSWID Section 2.8]: https://datatracker.ietf.org/doc/html/rfc9393#section-2.8
#[derive(Clone, Debug, PartialEq, StructToMap, StructToOneOrMore, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct SoftwareMetaEntry {
    #[cbor(tag = "43", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub activation_status: Option<String>,
    #[cbor(tag = "44", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel_type: Option<String>,
    #[cbor(tag = "45", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub colloquial_version: Option<String>,
    #[cbor(tag = "46", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cbor(tag = "47", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub edition: Option<String>,
    #[cbor(tag = "48", value = "Bool")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entitlement_data_required: Option<bool>,
    #[cbor(tag = "49", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entitlement_key: Option<String>,
    #[cbor(tag = "50", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generator: Option<String>,
    #[cbor(tag = "51", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub persistent_id: Option<String>,
    #[cbor(tag = "52", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product: Option<String>,
    #[cbor(tag = "53", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_family: Option<String>,
    #[cbor(tag = "54", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    #[cbor(tag = "55", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[cbor(tag = "56", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unspsc_code: Option<String>,
    #[cbor(tag = "57", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unspsc_version: Option<String>,
    //   * software-meta-extension,
    #[cbor(tag = "15", value = "Text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    //   global-attributes,
    #[cbor(value = "Array", cbor = "true")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub other: Option<Vec<Tuple>>,
}
